spring.application.name=ticketb
spring.application.port=8080
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=jay
spring.datasource.password=jay123
spring.jpa.hibernate.ddl-auto=update
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.data.redis.repositories.enabled=false
